# ===============================================
#  Arquivo: application.yml
#  Projeto: Alfabetiza+
#  Fun��o: Configura��es principais do backend
# ===============================================

spring:
  application:
    name: alfabetiza-plus-backend

  datasource:
    url: jdbc:postgresql://191.253.23.111:5432/AlfabetizaDev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # Flyway gerencia o esquema, n�o o Hibernate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


# ===============================================
# Perfil de Desenvolvimento
# ===============================================
---
#spring:
#  config:
#    activate:
#      on-profile: dev

#  datasource:
#    url: jdbc:postgresql://localhost:5432/alfabetizaplus_dev
#    username: alfplus
#    password: alfpass

#logging:
#  level:
#    root: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# ===============================================
# Perfil de Produ��o
# ===============================================
---
#spring:
#  config:
#    activate:
#      on-profile: prod

#  datasource:
#    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:alfabetizaplus}
#    username: ${DB_USER:alfplus}
#    password: ${DB_PASS:alfpass}

#  flyway:
#    enabled: true
#    baseline-on-migrate: true

#server:
#  port: ${PORT:8080}

#logging:
#  level:
#    root: WARN
